Repository ozguraslank/flexml, pull requests merged in 2024-12, with the labels that each got.

#10 Notebook Updation & tuning_size Param Remove from Model Tuning
  flexml/_model_tuner.py
  flexml/structures/supervised_base.py
  notebooks/classification_experiment.ipynb
  notebooks/regression_experiment.ipynb
  tests/test_classification.py
  tests/test_ml_models.py
  tests/test_regression.py
Labels: enhancement

#14 Added Cross Validation Feature & Revised Overall Structure for It
  flexml/_model_tuner.py
  flexml/config/supervised_config.py
  flexml/helpers/__init__.py
  flexml/helpers/cross_validation.py
  flexml/helpers/supervised_helpers.py
  flexml/structures/supervised_base.py
  tests/test_classification.py
  tests/test_cross_validation.py
  tests/test_ml_models.py
  tests/test_regression.py
Labels: enhancement

#15 Improved class and function structures & Added random_state value validator
  flexml/_model_tuner.py
  flexml/classification.py
  flexml/helpers/__init__.py
  flexml/helpers/cross_validation.py
  flexml/helpers/supervised_helpers.py
  flexml/helpers/validators.py
  flexml/logger/logger.py
  flexml/regression.py
  flexml/structures/supervised_base.py
  tests/test_classification.py
  tests/test_cross_validation.py
  tests/test_ml_models.py
  tests/test_regression.py
Labels: optimization

#16 Added MAPE and ROC-AUC evaluation metrics
  flexml/config/supervised_config.py
  flexml/helpers/supervised_helpers.py
  flexml/structures/supervised_base.py
Labels: enhancement

#17 Revised cross_validation structure & added shuffle param to SupervisedBase
  flexml/config/supervised_config.py
  flexml/helpers/__init__.py
  flexml/helpers/cross_validation.py
  flexml/helpers/validators.py
  flexml/structures/supervised_base.py
  tests/test_cross_validation.py
Labels: enhancement, optimization

#18 Added missing MAPE indicators in func docs and functions
  flexml/_model_tuner.py
  flexml/helpers/supervised_helpers.py
  flexml/helpers/validators.py
  flexml/regression.py
  flexml/structures/supervised_base.py
Labels: optimization

#21 Add save_model() Function, Tests, and Update Notebooks for Issue #20
  flexml/structures/supervised_base.py
  tests/test_classification.py
  tests/test_regression.py
Labels: enhancement
