Repository ozguraslank/flexml, pull requests merged in 2025-02, with the labels that each got.

#31 Predict feature is added and save_model is updated
  flexml/_feature_engineer.py
  flexml/classification.py
  flexml/regression.py
  flexml/structures/supervised_base.py
  tests/test_supervised.py
Labels: enhancement

#32 Error Fix / Eval Metrics Case handling, 'average' param configuration / Added predict_proba() function
  flexml/helpers/supervised_helpers.py
  flexml/helpers/validators.py
  flexml/structures/supervised_base.py
  tests/test_supervised.py
Labels: bug, enhancement

#34 Improved Feature Engineering Module & Mistake Fix on Handling n_folds Param's Default Var
  flexml/_feature_engineer.py
  flexml/structures/supervised_base.py
  tests/test_feature_engineering.py
Labels: bug, enhancement

#35 Added New ML Models, Revised the currents for Issue #19
  flexml/config/ml_models.py
Labels: enhancement, optimization
