Repository ozguraslank/flexml, pull requests merged in 2025-03, with the labels that each got.

#37 Error Fix and Improvement on Optuna and General Tuning Processes
  flexml/_model_tuner.py
  flexml/config/ml_models.py
  flexml/structures/supervised_base.py
  requirements.txt
Labels: bug

#38 Revised test_ml_models unittest and removed unnecessary model import in ml_models
  flexml/config/ml_models.py
  tests/test_ml_models.py
Labels: optimization

#39 Error fix and improvement at model evaluation
  flexml/_model_tuner.py
  flexml/helpers/supervised_helpers.py
  flexml/structures/supervised_base.py
Labels: bug, optimization

#41 General Bug Fixes and Improvements
  flexml/_model_tuner.py
  flexml/config/supervised_config.py
  flexml/helpers/validators.py
  flexml/structures/supervised_base.py
Labels: bug, optimization

#42 Fix to predict method for Classification problems
  flexml/structures/supervised_base.py
Labels: bug

#43 Filtered warning messages from models
  flexml/config/ml_models.py
Labels: bug

#44 Forced root logger to be overwritten by flexml
  flexml/logger/logger.py
Labels: bug

#45 Improved general model structure
  flexml/config/ml_models.py
  flexml/structures/supervised_base.py
Labels: optimization

#46 Bug fix / Added 'MAPE' to reverse_signed_eval_metrics
  flexml/config/supervised_config.py
Labels: bug

#47 Error fixes on Optuna module and start_experiment of SupervisedBase
  flexml/_model_tuner.py
  flexml/structures/supervised_base.py
Labels: bug

#49 1.1.0b1 Release
  README.md
  flexml/__init__.py
  img/start_guide_reg_output.jpg
  img/start_guide_reg_tuning_output.jpg
  notebooks/classification_experiment.ipynb
  notebooks/regression_experiment.ipynb
  setup.py
Labels: enhancement

#51 General fixes and improvements on 1.1.0b1 release
  flexml/_feature_engineer.py
  flexml/config/ml_models.py
  flexml/structures/supervised_base.py
Labels: bug, optimization

#52 General bug fixes and optimizations
  flexml/config/ml_models.py
  flexml/helpers/supervised_helpers.py
  flexml/helpers/validators.py
  flexml/structures/supervised_base.py
  requirements-test.txt
  requirements.txt
  tests/test_ml_models.py
Labels: bug, optimization

#53 Added Codecov coverage workflow
  .github/workflows/tests.yml
  requirements-test.txt
Labels: enhancement

#54 Added code coverage badge to README
  README.md
Labels: enhancement

#55 Disabled codecov-commenter to comment on PRs
  codecov.yml
Labels: optimization

#56 Improved README badges
  README.md
Labels: optimization

#57 Improved Unit Tests
  flexml/_model_tuner.py
  tests/test_cross_validation.py
  tests/test_ml_models.py
  tests/test_supervised.py
Labels: optimization

#58 Error raise structure revise of helper functions / if -> Raise Exception() to assert
  flexml/helpers/cross_validation.py
  flexml/helpers/supervised_helpers.py
  flexml/helpers/validators.py
Labels: optimization

#59 Reverted exception structure to previous version and improved unittest
  flexml/helpers/cross_validation.py
  flexml/helpers/validators.py
  tests/test_cross_validation.py
Labels: optimization

#61 Improved unit test coverage of the functions at flexml/helpers
  flexml/helpers/cross_validation.py
  flexml/helpers/validators.py
  tests/test_cross_validation.py
  tests/test_helpers.py
Labels: enhancement, optimization

#62 Error fix / Added 'category' dtype to categorical data check in encoders
  flexml/_feature_engineer.py
  flexml/structures/supervised_base.py
Labels: bug
